### ISSUE TITLE
Max Height Limit

### ISSUE THREAD

**Issue by TheRealJAnderson** [hanskellner/Fusion360Image2Surface#10]
I love this add in a ton and what I'd love to do is have a max height higher than 25mm. Is this possible to implement?

**Comment by hanskellner** [comment]
Hi @TheRealJAnderson - Yes, let me take a look at what I can do.

**Comment by hanskellner** [comment]
Ok, I've bumped up the parameter ranges (all in millimeters):

- 'pixelStep' (1.0 -> 50.0)
- 'meshStep' (0.10 -> 10.0)
- 'maxHeight' (1.0 -> 500.0)

Grab the newest version from here and copy the file into the same location that you have the addin installed.  Note, be sure to first exit Fusion 360 then start after changes installed.  @TheRealJAnderson

**Comment by TheRealJAnderson** [comment]
That's awesome! Thanks for updating that. It works well with some test files. I'll be trying out a terrain map tomorrow with it.
