### ISSUE TITLE
How to take a Image2Surface Surface and put it on the face of an existing model in Fusion

### ISSUE THREAD

**Issue by azmetalfab** [hanskellner/Fusion360Image2Surface#13]
We got Image2surface working and created a surface in fusion, however, we are stuck with how to then combine that onto an existing model. Given that the utility is here I thought we'd ask here even though it's more Fusion HELP than the utility !!

We have a model that we designed and want to cut on our router table in wood, the designer would like a "hand carved" look to the finish when the design is cut. We have used Image2surface to create a surface that looks like it's hand carved, however, we are not able to find a good way to use this surface to replace/merge with a face in our model.
 
Just to be clear we're not looking for rendering/appearance assistance, we need a 3D surface on the finished model so it will go through CAM and produce the 3D profile to cut

**Comment by hanskellner** [comment]
@azmetalfab If I understand you correctly, I think the following Instructable contains steps that may help you:

https://www.instructables.com/id/3D-CNC-Relief-Sculpture-Fusion-360/

See the section "PLACE THE SURFACE WITHIN A BLOCK" and if that helps with what you need to do.
