### ISSUE TITLE
Image2Surface Script Failed : the relative resourceFolder path not found

### ISSUE THREAD

**Issue by marc1henry** [hanskellner/Fusion360Image2Surface#14]
when trying to upload any image, fusion 360 says "Image2Surface Script Failed : the relative resourceFolder path not found". what can I do?

thank you so much!

best
marc
![we](https://user-images.githubusercontent.com/62402249/77111117-0f3ac500-6a27-11ea-84cf-e74c8f2c4ef3.JPG)

**Comment by hanskellner** [comment]
Hi @marc1henry - I just started Fusion 360 (Mac) and ran the addin without any issues.  A few questions:

- Are you running Mac or Windows?
- Are you running the current version of Fusion?
- Did you install the Image2Surface addin from Github or the app store?

One thought it that the addin hasn't been installed correctly.  Have you unarchived all of the files into a new and empty folder?  And when unarchiving, did the contained folders also get created (which is required)?

Thanks.

**Comment by marc1henry** [comment]
I was able to fix it with your instructions! Thanks and best

Marc
