### ISSUE TITLE
Generating triangle meshes, not quad

### ISSUE THREAD

**Issue by semiconducted** [hanskellner/Fusion360Image2Surface#15]
I'm wondering if something happened with an updated version of Fusion breaking your script or if it has something to do with the type of image I am trying to mesh.

​When I use the script to generate my mesh (from a thin "lightning bolt"), the script creates a triangle mesh. 
​When I attempt to Convert Quad Mesh to T-SPline, it fails citing that my mesh is not a quad mesh: "​Warning: Mesh to T-Spline conversion aborted."
​
​This happens with both a tiny 2500 polygon mesh and the larger one that threw the attached error message.

![screen 2020-06-25 at 6 34 41 PM](https://user-images.githubusercontent.com/1928889/85802615-506ffe80-b713-11ea-928c-e39b72433f73.png)

**Comment by hanskellner** [comment]
Hi @semiconducted -

Please check your Fusion mesh preferences.  There's the setting "Triangulate mesh polygons".  If that's checked then the mesh created by the add-in will be triangles and not quads.

**Comment by semiconducted** [comment]
YES! That fixed the problem. (I finally got back to this project to test out the solution).

THANK YOU for making such a great Add-In!

Attached are a few other screenshots I took if you choose to use them in the README.md.

i.e. 
After selecting the mesh you should see the following options:
![screen 2020-08-19 at 3 31 03 PM](https://user-images.githubusercontent.com/1928889/90685972-9c818000-e238-11ea-926f-11b10a029829.png)

I found changing the Display Mode also helpful:
![screen 2020-08-19 at 3 31 41 PM](https://user-images.githubusercontent.com/1928889/90686191-f97d3600-e238-11ea-96a3-150ab2d7ee07.png)
![screen 2020-08-19 at 3 31 33 PM](https://user-images.githubusercontent.com/1928889/90686193-fa15cc80-e238-11ea-8a21-af7cf971b1a2.png)
