### ISSUE TITLE
Javascripted Add-Ins no longer supported in Fusion 360

### ISSUE THREAD

**Issue by cel22262** [hanskellner/Fusion360Image2Surface#16]
Will this add-in be updated to work with the latest Fusion 360 release?
Latest announcement indicates add-ins should be written in Python or C++ (JavaScript no longer supported)

------------------------------------------
Sorry, didn't see the previous ticket re:JavaScript. (Thou I did look at the package and noticed all the JS stuff)
However I'm experiencing issues with the the add-in within the UI. Script runs but then the drop-downs in the UI top menus stop working, and in the project space the feature menus toggle on/off. (click any where...)

I originally thought these behaviors were contributed to the JS announcements.

**Comment by hanskellner** [comment]
HI @cel22262 - 

Yes, I'll update this add-in in the event the upcoming retirement of JS causes it to fail.  Too many people are using it.

Regarding your issue, I'll do some testing to see if I can reproduce.  Are you running on Windows or Mac?

**Comment by hanskellner** [comment]
Python version exists.
