### ISSUE TITLE
Image2Surface not opening small image

### ISSUE THREAD

**Issue by HJ-vdB** [hanskellner/Fusion360Image2Surface#18]
It seems my Image2Surface stopped working.
I am using it only now and then, however, it always worked fine until now.
I removed the previous installation, downloaded the latest from Github, reinstalled it and it opens up and seems to be working well in the Fusion 360 environment. I created a base feature (history-free). even after this it does not open even a 180 x 200 .jpg file. I tried also to convert it to .BMP, .TIF etc. but it is not working.
When I drag the file it does not allow the action, (the arrow change into a crossed out 0). When I select the file, it accepts it, and show the file name and size, but it does not open it.

**Comment by hanskellner** [comment]
Hi @HJ-vdB - 

I'll do some testing with the current version and report back.

Thanks.

**Comment by hanskellner** [comment]
Hi @HJ-vdB - 

I just ran it on several images, all larger than the size you are trying, and they all imported correctly.

Please try the penny sample image that comes with the add-in.  It's in the folder:

<Image2Surface folder>/Resources/images/penny_depthmap_500.jpg

If that fails to load, please provide more information:

- Version of Fusion 360 and platform (Mac/Windows)
- The image file (if willing to share)

Thanks.

**Comment by HJ-vdB** [comment]
Thank you kindly Hans,

 

I tried penny_depthmap_500.jpg but it also failed.

 

Please note, after I did a clean install of Fusion 360 as well as Image2Surface, it gave me a message: “Your graphics card does not seem to support WebGL. Find out to get it here.” There is no link to it and it was only showed this once, afterward it just does not do anything except that the file is shown next to “Choose File” and the file Information is shown except not the Surface Information. See screenshot attached.

 

Version of Fusion 30 from About in Fusion: 

2.0.12164
Active Plan: Fusion 360, Subscription
Windows 10 Pro 21H2 x86_64 (22000.434)

Although when I look at my indows, it says I am running Windows 11 for x64-based Systems.

I also added a few files I wanted to load but was not able to.

Kind regards,
 
Herman van den Berg
 
                           ***@***.***> ***@***.***

             +31 62 372 7493  or  +27 78 002 2003

**Comment by HJ-vdB** [comment]
Dear Hans,

 

It seems that I have accidentally found the answer.

 

I tested the WebGL and everything works as it should.

 

We had a power failure and I was working on battery power and the main screen was off. I tried it once more in this configuration and it worked!

 

Thank you kindly for trying to help!

Kind regards,
 
Herman van den Berg
 
                           ***@***.***> ***@***.***

             +31 62 372 7493  or  +27 78 002 2003 

 

From: ***@***.*** ***@***.***> 
Sent: Wednesday, February 2, 2022 10:16 PM
To: 'hanskellner/Fusion360Image2Surface' ***@***.***>; 'hanskellner/Fusion360Image2Surface' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [hanskellner/Fusion360Image2Surface] Image2Surface not opening small image (Issue #18)

 

Thank you kindly Hans,

 

I tried penny_depthmap_500.jpg but it also failed.

 

Please note, after I did a clean install of Fusion 360 as well as Image2Surface, it gave me a message: “Your graphics card does not seem to support WebGL. Find out to get it here.” There is no link to it and it was only showed this once, afterward it just does not do anything except that the file is shown next to “Choose File” and the file Information is shown except not the Surface Information. See screenshot attached.

 

Version of Fusion 30 from About in Fusion: 

2.0.12164
Active Plan: Fusion 360, Subscription
Windows 10 Pro 21H2 x86_64 (22000.434)

Although when I look at my indows, it says I am running Windows 11 for x64-based Systems.

I also added a few files I wanted to load but was not able to.

Kind regards,
 
Herman van den Berg
 
                           ***@***.***> ***@***.***

             +31 62 372 7493  or  +27 78 002 2003

**Comment by hanskellner** [comment]
Hi @HJ-vdB -

Ok, that's good to know!  Glad you were able to get it working.

And please let me know if there are any improvements to the add-in that you would like.  I'm planning to update it and any input is appreciated.

Thanks.

**Comment by HJ-vdB** [comment]
Dear Hans,

 

Thank you kindly for asking some input for your development!

 

I consider that it could be very interesting to be able to modify the B/W, Contrast and light of the picture while it is loaded in your ap so one can adjust how the conversion will happen. Not sure if this is possible but I appreciate the opportunity to add functionality

 

Kind regards,
 
Herman van den Berg
 
                           ***@***.***> ***@***.***

             +31 62 372 7493  or  +27 78 002 2003
