### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by stefream** [hanskellner/Fusion360Image2Surface#9]
I've been trying to get image2surface to interface with Fusion. I can get it to acknowledge that there is a new addin running, but that is it. I've followed the guide attached exactly, and I've tried other methods as well. Nothing works. Help!

**Comment by hanskellner** [comment]
Hi @stefream - When you are in the Design environment, do you see the menu item for Image2Surface under the Tools->ADD-INS dropdown?

**Comment by stefream** [comment]
Yes. I can get Fusion to acknowledge the add-in, but when I run it, nothing happens.

**Comment by hanskellner** [comment]
Hi @stefream - Please try re-installing the add-in.  Within the Fusion AddIn panel, stop Image2Surface if it's running then remove it from the list.  Exit Fusion.

Locate the folder containing the Image2Surface addin and remove all of the file.  Be sure the folder only contains the files from Image2Surface be deleting them.

Download the ZIP from here and unarchive the files.  Rename the folder created that contains the files to "Image2Surface".  Copy/Move that folder to Fusion's AddIns folder.

Start Fusion and install Image2Surface in the Tools->ADD-INS dialog.

**Comment by stefream** [comment]
Got it, thanks!
